S02 us31 footer
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #113
Opened 2022-10-30 15:44 UTC by V-Gillet

2022-10-30 19:36 UTC, charier963 approved these changes

2022-11-02 14:17 UTC, HuHoudas submitted a review, later dismissed

2022-11-02 16:13 UTC, NefytZ approved these changes

2022-11-03 07:54 UTC, sblondeau requested changes

2022-11-03 07:54 UTC, sblondeau commented on src/View/Components/_footer.html.twig
> +				<img src="/assets/images/FFM-logo.png" alt="logo of FFM">
hum, c'est pas sensé etre administrable les partenaires ?! dans ce cas pas d'images dans assets/image car ce sera des images uploadées

2022-11-03 07:54 UTC, sblondeau commented on src/View/Components/_footer.html.twig
> +				<img src="/assets/images/FFM-logo.png" alt="logo of FFM">
l'afichage doit etre dynamique depuis une table partner

2022-11-03 07:54 UTC, sblondeau commented on src/View/Components/_footer.html.twig
> +					<a href="" class="text-light">A propos</a>
À propos

2022-11-03 08:21 UTC, V-Gillet commented on src/View/Components/_footer.html.twig
> +				<img src="/assets/images/FFM-logo.png" alt="logo of FFM">
Si on a le temps on veut le rendre dynamique. Je vais créer la table pour prévoir le CRUD.

2022-11-03 08:24 UTC, V-Gillet commented on src/View/Components/_footer.html.twig
> +					<a href="" class="text-light">A propos</a>
La touche n'est pas sur mon clavier, c'est trop dur ! :D 
Je corrige ça, merci

2022-11-07 14:58 UTC, HuHoudas approved these changes

2022-11-07 16:22 UTC, merged