fixed the titles sizes, colors and borders of homepage
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #115
Opened 2022-10-31 16:44 UTC by V-Gillet

2022-10-31 17:03 UTC, HuHoudas approved these changes

2022-11-02 08:51 UTC, NefytZ submitted a review, later dismissed

2022-11-02 08:51 UTC, HuHoudas submitted a review, later dismissed

2022-11-02 09:37 UTC, Zakari-B requested changes

2022-11-02 09:37 UTC, Zakari-B commented on src/View/Home/index.html.twig
>  {% block header %}
Le fichier présentation.css a été supprimé du commit, mais il est encore importé en ligne 5 de ce fichier.

2022-11-02 10:14 UTC, sblondeau approved these changes

2022-11-02 10:14 UTC, merged