S02 us125 header section sport
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #140
Opened 2022-11-06 16:18 UTC by V-Gillet

2022-11-06 18:04 UTC, HuHoudas approved these changes

2022-11-07 13:48 UTC, NefytZ approved these changes

2022-11-07 16:28 UTC, HuHoudas submitted a review, later dismissed

2022-11-08 09:52 UTC, sblondeau requested changes

2022-11-08 09:52 UTC, sblondeau commented on database.sql
> +        "assets/images/auto_cover.webp",
pour les images, il ne faut stocker que le nom, pas le chemin total
et ce sont des images administrables, donc elles devront etre dans un dossier uploads non versionné, pas dans assets/images

2022-11-08 12:45 UTC, sblondeau approved these changes

2022-11-08 12:45 UTC, merged