S02US03 fix responsive card + design card
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #142
Opened 2022-11-07 16:06 UTC by HuHoudas

2022-11-07 16:12 UTC, V-Gillet approved these changes

2022-11-07 16:31 UTC, Zakari-B requested changes

2022-11-07 16:31 UTC, Zakari-B commented on public/assets/css/card.css
> +@media (min-width: 992px){
Est-ce que la card peut passer en width 75% ? Si oui, privilégier la classe bootstrap plutôt que la media query.

2022-11-07 16:32 UTC, HuHoudas commented on public/assets/css/card.css
> +@media (min-width: 992px){
alors je veux bien mais on peux pas faire un breakpoint avec bootstrap ou alors j'ai pas comprit

2022-11-07 16:33 UTC, HuHoudas commented on src/View/Home/index.html.twig
> +							<p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
normal c'été qu'un fix pour le design

2022-11-08 09:53 UTC, sblondeau requested changes

2022-11-08 09:53 UTC, sblondeau commented on database.sql
> +INSERT INTO `event` (imgPath, title, paragraph) VALUES ("assets/images/Card1.jpeg", "Compétition rallye Orleans", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id sodales tellu
meme pb que l'autre PR sur le chemin des images

2022-11-08 09:53 UTC, sblondeau commented on src/View/Home/index.html.twig
> +				<a href='#' class="all-event text-white px-2">Voir tous les évènements</a>
double quote dans le html

2022-11-09 13:29 UTC, V-Gillet approved these changes

2022-11-09 14:07 UTC, sblondeau approved these changes

2022-11-09 14:07 UTC, merged