S02 us29 bureau page
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #144
Opened 2022-11-08 22:11 UTC by V-Gillet

2022-11-08 22:28 UTC, HuHoudas approved these changes

2022-11-09 08:50 UTC, sblondeau requested changes
traduire bureau ?
faire une seule table pour tous les membres
ça va beaucoup simplifier ton code, on en reparle si besoin car y a bien plusieur US à gérer, coté membre, coté conseil,

2022-11-09 08:50 UTC, sblondeau commented on public/assets/css/bureau.css
> +        margin-inline: 0 !important;
pas de !important

2022-11-09 08:50 UTC, sblondeau commented on src/Controller/BureauController.php
> +class BureauController extends AbstractController
on serait pas plutot sur du Board que du Bureau in english ?

2022-11-09 08:50 UTC, sblondeau commented on src/Controller/BureauController.php
> +            "conseilAdminstrateurs" => $conseilAdmin,
en anglais

2022-11-09 08:50 UTC, sblondeau commented on src/Model/ConseilAdministrationManager.php
> +class ConseilAdministrationManager extends AbstractManager
en anglais ?
mais sinon les personne au conseil sont aussi des membres a priori ? 
ça m'aurait semblé plus logique d'avoir une seule table member avec un "role" possible et si le role est pas null, c'est qu'on est sur un membre du conseil ?

2022-11-09 08:50 UTC, sblondeau commented on src/View/Bureau/bureau.html.twig
> +				<!-- rendre cette partie dynamique avec une relation avec section -->
du coup c'est une autre US. Donc plutot que de mettre un commentaire et de le faire "en dur", ne le fais pas, tout simplement !
Retire tout ça dès maintenant car de toute façon tu auras à le retirer plus tard quand tu le rendras dynamique

2022-11-09 22:31 UTC, sblondeau requested changes

2022-11-09 22:31 UTC, sblondeau commented on src/Model/BoardManager.php
> +        $query = 'SELECT * FROM ' . static::TABLE . ' WHERE is_board_member = ' . $isBoardMember;
self::TABLE

2022-11-09 22:31 UTC, sblondeau commented on src/Controller/BoardController.php
> +        $members = $boardManager->selectAll('firstname');
je croyais que les membres et les boardmembers n'étaient pas inclus
là si tu fais selectAll, c'est que tous les boardMembers sont aussi des membres ?

2022-11-10 09:31 UTC, sblondeau approved these changes

2022-11-10 09:45 UTC, sblondeau approved these changes

2022-11-10 09:45 UTC, merged