S02US05 ajouter de la partie nous rejoindre
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #148
Opened 2022-11-09 15:47 UTC by HuHoudas

2022-11-09 16:20 UTC, V-Gillet approved these changes

2022-11-09 16:43 UTC, sblondeau requested changes

2022-11-09 16:43 UTC, sblondeau commented on src/View/Home/index.html.twig
> +						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id sodales tellus. Pellentesque in lorem vitae risus fermentum rutrum. Vestibulum sed libero eget diam fringilla convallis vi
pas de lorem ipsum sur les parties non administrables 
si besoin demandez un texte au client

2022-11-10 08:27 UTC, sblondeau approved these changes

2022-11-10 08:46 UTC, NefytZ submitted a review, later dismissed

2022-11-10 09:52 UTC, merged