made navbar admin and route to admin homepage
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #152
Opened 2022-11-09 21:52 UTC by V-Gillet

2022-11-10 08:09 UTC, HuHoudas approved these changes

2022-11-10 09:50 UTC, sblondeau requested changes

2022-11-10 09:50 UTC, sblondeau commented on src/View/admin_layout.html.twig
> +<!doctype html>
le admin_layout et le layour (visiteur) doit extends un base_layout qui contiendra le DOCTYPE / HTML de base

2022-11-10 10:40 UTC, Zakari-B commented on src/View/Components/_admin_navbar.html.twig
> +{% block navbar %}
Pas de block dans ce component.

2022-11-10 11:11 UTC, V-Gillet commented on src/View/Components/_admin_navbar.html.twig
> +{% block navbar %}
Effectivement, corrigé !

2022-11-14 08:40 UTC, sblondeau approved these changes

2022-11-14 08:40 UTC, merged