S03 us186 layout add sports sections
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #189
Opened 2022-11-15 11:41 UTC by V-Gillet

2022-11-15 13:05 UTC, HuHoudas submitted a review, later dismissed

2022-11-15 21:31 UTC, HuHoudas approved these changes

2022-11-15 21:33 UTC, NefytZ approved these changes

2022-11-16 09:07 UTC, sblondeau requested changes
c'est quoi la US ? si c'est ajouter un sport (ça a l'air d'être ça) il manque tout le traitement PHP/SQL

PS: on s'y retrouve pas sur votre projet, il me faudrait une vue filtrée avec le sprint en cours à jour !

2022-11-16 14:58 UTC, closed without merging