partners
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #192
Opened 2022-11-15 17:53 UTC by NefytZ

2022-11-15 22:08 UTC, V-Gillet requested changes

2022-11-15 22:08 UTC, V-Gillet commented on public/assets/css/partner.css
> +    padding: 5px;
Peut-être fait en class bootstrap.

2022-11-15 22:08 UTC, V-Gillet commented on public/assets/css/partner.css
> +    margin: auto;
Class bootstrap :)

2022-11-15 22:08 UTC, V-Gillet commented on public/assets/css/partner.css
> +    margin: auto;
Pareil :p

2022-11-15 22:08 UTC, V-Gillet commented on src/View/Partners/partner.html.twig
> +{% extends "layout.html.twig"%}
Sur dev c'est devenu "visitor_layout.html.twig". Mets le même si ça casse ton code pour l'instant.

2022-11-15 22:08 UTC, V-Gillet commented on src/View/Partners/partner.html.twig
> +{% block stylesheet %}
On a aussi modifié ce bloc, pour afficher un stylesheet sur un block enfant de visitor_layout ou admin_layout il faut un block : 
{% block stylesheetGrandChild %}

2022-11-15 22:08 UTC, V-Gillet commented on src/routes.php
> +    'partner' => ['PartnerController', 'partner',]
Le nom de la route plutot en FR pour M. Painchault :D

2022-11-15 22:08 UTC, V-Gillet commented on src/routes.php
> +    'partner' => ['PartnerController', 'partner',]
Et du coup pense à relier ta page à la navbar avec un "href="/partenaires", par exemple.

2022-11-16 11:10 UTC, HuHoudas submitted a review, later dismissed

2022-11-16 14:06 UTC, sblondeau requested changes

2022-11-16 14:06 UTC, sblondeau commented on src/View/Partners/partner.html.twig
> +    <a class="col-6 col-md-3 d-flex justify-content-center" href="{{ partner.url }}"><img class="logo"
manque le alt sur l'img

2022-11-16 14:06 UTC, sblondeau commented on database.sql
> +        "/assets/images/Partner-img/RCVL-logo.png",
juste le nom de l'image, pas le path complet
et ça devrait pas etre uploadable plutot ? donc dans upload

2022-11-17 14:02 UTC, HuHoudas approved these changes

2022-11-17 14:47 UTC, sblondeau approved these changes

2022-11-17 14:47 UTC, merged