remove padding admin event card
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #306
Opened 2022-11-22 16:08 UTC by HuHoudas

2022-11-22 21:17 UTC, V-Gillet submitted a review, later dismissed

2022-11-23 07:49 UTC, sblondeau requested changes

2022-11-23 07:49 UTC, sblondeau commented on src/View/AdminEvent/AdminEvent.html.twig
> +			<div class="admin-view-card col-9 card container-xxl px-0">
pas de padding horizontal sur la meme ligne qu'un col ou un row. 
c'est excessivement compliqué votre truc, j'ai un col, dans un row dans un col dans un row avec un container-xxl en plus :crazy:

2022-11-23 08:36 UTC, Zakari-B approved these changes

2022-11-23 11:08 UTC, NefytZ approved these changes

2022-11-23 11:13 UTC, Zakari-B approved these changes

2022-11-23 11:13 UTC, merged