fix size card on gouvernance admin
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #309
Opened 2022-11-22 16:29 UTC by NefytZ

2022-11-22 21:20 UTC, V-Gillet approved these changes

2022-11-23 07:50 UTC, sblondeau requested changes

2022-11-23 07:50 UTC, sblondeau commented on src/View/AdminBoard/AdminBoard.html.twig
> -			<div class="admin-view-card col-9 card container-xxl">
meme retour que sur la pr d'Hugo, bien trop compliqué votre truc, vous n'utilisez pas bien le système de grid de bootstrap :( 
j'ai pas à avoir un container-xxl dans un row au meme niveau qu'un col-9 :(

2022-11-23 09:09 UTC, HuHoudas approved these changes

2022-11-23 09:12 UTC, sblondeau approved these changes

2022-11-23 09:12 UTC, merged