S1 us09 paragraph presentation association
WildCodeSchool/2022-09-php-orleans-project-ecurieorleans pull request #91
Opened 2022-10-27 14:31 UTC by charier963

crée une demande de versification.

2022-10-27 14:44 UTC, HuHoudas approved these changes

2022-10-27 14:55 UTC, V-Gillet submitted a review, later dismissed

2022-10-27 14:57 UTC, HuHoudas submitted a review, later dismissed

2022-10-28 11:07 UTC, sblondeau requested changes

2022-10-28 11:07 UTC, sblondeau commented on public/assets/css/presentation.css
> +h2 {
déjà dans style.css à l'identique

2022-10-28 11:07 UTC, sblondeau commented on src/Model/FormManager.php
> +class FormManager extends AbstractManager
tjs là ? à virer non ?

2022-10-28 11:07 UTC, sblondeau commented on src/View/form/Form.html.twig
> +    <p>Find a complete CRUD example on <a href="/items">/items</a> page.</p>
à faire

2022-10-28 11:15 UTC, sblondeau approved these changes

2022-10-28 11:15 UTC, merged